### ISSUE TITLE
Combining gridswitch with advanced filter plugin

### ISSUE THREAD

**Issue by vibe9** [CodyHouse/cd-grid-switch-changelog#2]
I am using the gridswitch plugin with the codyframe advanced filter plugin and have it working except the classes are not getting assigned correctly after you filter out and then toggle the grid. I can send you a working URL example via email but I can't post it publicly due to the project being confidential.

**Comment by claudia-romano** [comment]
Hi there,
I just tested the two components combined and everything seems to be working fine:
https://www.dropbox.com/s/bv1owbc0gpmi9y4/grid-switcher.mp4?dl=0

Please make sure to follow the instructions we provide on the Info page of the components:
https://codyhouse.co/ds/components/info/grid-switch
https://codyhouse.co/ds/components/info/advanced-filter

Cheers

**Comment by vibe9** [comment]
Hi Claudia

Appreciate the follow up! 

I always read the instructions, thoroughly :-)

Here’s a direct link to a working example that follows your instructions. http://client.vibe9design.com/ste.marie/fullsite/projects.html <http://client.vibe9design.com/ste.marie/fullsite/projects.html>

If you select Typology -> Category 1, then switch to the grid, then select Typology -> Category 2 you’ll see that the classes are not inherited and the first div does not get the column classes.



Cheers
Terry

**Comment by claudia-romano** [comment]
Hi Terry, unfortunately we are not able to check custom code. If you can create a demo with no custom CSS/JS, we can check that out.
From my video you can see that combining the two components does not create the issue.

Cheers

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
